Resources:
  MeasurmentsDynamoDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
      - AttributeName: measurementId
        AttributeType: S
      - AttributeName: measurementTime
        AttributeType: S
      KeySchema:
      - AttributeName: measurementId
        KeyType: HASH
      - AttributeName: measurementTime
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1